version: '3.7'

services:
  bootnode:
    hostname: bootnode
    #env_file:
    #  - env
    image: geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=kikkelis
        #- USER_ID=1000
        #- GROUP_ID=1000
    volumes:
       - ./bootnode:/home/geth/.ethereum/
    command:
      --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5"
      --nodiscover
      --ipcdisable
      --networkid=1234
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:
        #ipv4_address: 172.16.254.1

  endpoint:
    hostname: endpoint
    #env_file:
    #  - env
    image: geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=kikkelis
        #- USER_ID=1000
        #- GROUP_ID=1000
    depends_on:
      - bootnode
    volumes:
       - ./endpoint:/home/geth/.ethereum/
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@bootnode:30303"
      --allow-insecure-unlock
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin,personal"
      --http.corsdomain="*"
      --networkid=1234
      --netrestrict="172.16.254.0/28"
    ports:
      - "8545:8545"
    networks:
      priv-eth-net:
        #ipv4_address: 172.16.254.2

  miner:
    hostname: miner
    #env_file:
    #  - env
    image: geth-client
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=kikkelis
        #- USER_ID=1000
        #- GROUP_ID=1000
    depends_on:
      - bootnode
    volumes:
       - ./miner:/home/geth/.ethereum/
    command:
      --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@bootnode:30303"
      --mine
      --miner.threads=1
      --networkid=1234
      --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:
        #ipv4_address: 172.16.254.3

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28
        # gateway: 172.16.254.0
  
